name: Preprocessing
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install pandas scikit-learn numpy joblib
      - run: cd preprocessing && python automate_AyodyaEnhanayoan.py
